version: "3"
services:
  redis:
    image: redis
    container_name: crawler-redis
    command: redis-server

  web:
    build: .
    container_name: crawler-web
    command: sh web.sh
    volumes:
      - .:/live_crawler
    ports:
      - "3000:3000"
    links:
      - redis