version: "3"
services:
  web:
    build: .
    container_name: crawler-web
    command: bundle exec thin start -p 3000 -e production
    volumes:
      - .:/crawler_with_sinatra
    ports:
      - "3000:3000"
    network_mode: "host"